--  pegamos DCColo.sql

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.


BEGIN;


CREATE TABLE IF NOT EXISTS public.asistente_evento
(
    id_asistente serial NOT NULL,
    codigo_evento character varying(20) COLLATE pg_catalog."default",
    run_asistente character varying(12) COLLATE pg_catalog."default",
    nombre_asistente character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT asistente_evento_pkey PRIMARY KEY (id_asistente)
);

CREATE TABLE IF NOT EXISTS public.cargo
(
    id_cargo serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cargo_pkey PRIMARY KEY (id_cargo)
);

CREATE TABLE IF NOT EXISTS public.comuna
(
    codigo_comuna integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigo_region integer NOT NULL,
    CONSTRAINT comuna_pkey PRIMARY KEY (codigo_comuna)
);

CREATE TABLE IF NOT EXISTS public.contacto_empresa
(
    id_contacto serial NOT NULL,
    rut_empresa character varying(15) COLLATE pg_catalog."default",
    run_persona character varying(12) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default",
    cargo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT contacto_empresa_pkey PRIMARY KEY (id_contacto)
);

CREATE TABLE IF NOT EXISTS public.cuota
(
    id_cuota serial NOT NULL,
    id_membresia integer,
    mes integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    monto_total integer NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cuota_pkey PRIMARY KEY (id_cuota)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    rut_empresa character varying(15) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT empresa_pkey PRIMARY KEY (rut_empresa)
);

CREATE TABLE IF NOT EXISTS public.evento
(
    codigo_evento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    fecha_evento date NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    codigo_sucursal character varying(10) COLLATE pg_catalog."default",
    tipo_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    identificador_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT evento_pkey PRIMARY KEY (codigo_evento)
);

CREATE TABLE IF NOT EXISTS public.lugar
(
    codigo_lugar character varying(15) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    capacidad integer NOT NULL,
    codigo_sucursal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tipo_lugar character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT lugar_pkey PRIMARY KEY (codigo_lugar)
);

CREATE TABLE IF NOT EXISTS public.membresia
(
    id_socio integer NOT NULL,
    id_socio_titular integer,
    anio integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    monto_base integer NOT NULL,
    CONSTRAINT membresia_pkey PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.naci
(
    run character varying(12) COLLATE pg_catalog."default",
    nac date
);

CREATE TABLE IF NOT EXISTS public.pago_cuota
(
    id_pago_cuota serial NOT NULL,
    cuota_numero integer,
    fecha_pago date NOT NULL,
    monto_pagado integer NOT NULL,
    medio_pago character varying(30) COLLATE pg_catalog."default",
    id_socio integer,
    CONSTRAINT pago_cuota_pkey PRIMARY KEY (id_pago_cuota)
);

CREATE TABLE IF NOT EXISTS public.pago_evento
(
    id_pago_evento serial NOT NULL,
    codigo_evento character varying(20) COLLATE pg_catalog."default",
    fecha_pago date NOT NULL,
    monto integer NOT NULL,
    tipo_pago character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pago_evento_pkey PRIMARY KEY (id_pago_evento)
);

CREATE TABLE IF NOT EXISTS public.pago_reserva
(
    id_pago_reserva serial NOT NULL,
    codigo_reserva character varying(20) COLLATE pg_catalog."default",
    fecha_pago date NOT NULL,
    monto integer NOT NULL,
    medio_pago character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT pago_reserva_pkey PRIMARY KEY (id_pago_reserva)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    run character varying(12) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default",
    telefono_celular character varying(20) COLLATE pg_catalog."default",
    telefono_alternativo character varying(20) COLLATE pg_catalog."default",
    direccion_calle character varying(150) COLLATE pg_catalog."default",
    codigo_comuna integer,
    fecha_nacimiento date,
    CONSTRAINT persona_pkey PRIMARY KEY (run)
);

CREATE TABLE IF NOT EXISTS public.persona_cargo
(
    id_persona_cargo serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    id_cargo integer,
    codigo_sucursal character varying(10) COLLATE pg_catalog."default",
    fecha_inicio date NOT NULL,
    fecha_termino date,
    CONSTRAINT persona_cargo_pkey PRIMARY KEY (id_persona_cargo)
);

CREATE TABLE IF NOT EXISTS public.precio_lugar
(
    id_precio serial NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    tipo_precio character varying(10) COLLATE pg_catalog."default" NOT NULL,
    dia_semana character varying(15) COLLATE pg_catalog."default",
    hora_inicio time without time zone,
    hora_termino time without time zone,
    fecha_inicio date,
    fecha_fin date,
    monto integer NOT NULL,
    CONSTRAINT precio_lugar_pkey PRIMARY KEY (id_precio)
);

CREATE TABLE IF NOT EXISTS public.region
(
    codigo_region integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (codigo_region)
);

CREATE TABLE IF NOT EXISTS public.relacion_socio
(
    id_relacion serial NOT NULL,
    id_socio_titular integer,
    id_socio_dependiente integer,
    parentesco character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT relacion_socio_pkey PRIMARY KEY (id_relacion)
);

CREATE TABLE IF NOT EXISTS public.reserva
(
    codigo_reserva character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    run_reservante character varying(12) COLLATE pg_catalog."default",
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT reserva_pkey PRIMARY KEY (codigo_reserva)
);

CREATE TABLE IF NOT EXISTS public.socio
(
    id_socio serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    tipo_socio character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    codigo_sucursal_base character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT socio_pkey PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.sucursal
(
    codigo_sucursal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    codigo_comuna integer,
    CONSTRAINT sucursal_pkey PRIMARY KEY (codigo_sucursal)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    email_login character varying(150) COLLATE pg_catalog."default" NOT NULL,
    clave_encriptada character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_usuario character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.asistente_evento
    ADD CONSTRAINT asistente_evento_codigo_evento_fkey FOREIGN KEY (codigo_evento)
    REFERENCES public.evento (codigo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comuna
    ADD CONSTRAINT comuna_codigo_region_fkey FOREIGN KEY (codigo_region)
    REFERENCES public.region (codigo_region) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contacto_empresa
    ADD CONSTRAINT contacto_empresa_rut_empresa_fkey FOREIGN KEY (rut_empresa)
    REFERENCES public.empresa (rut_empresa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cuota
    ADD CONSTRAINT cuota_id_membresia_fkey FOREIGN KEY (id_membresia)
    REFERENCES public.membresia (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lugar
    ADD CONSTRAINT lugar_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.membresia
    ADD CONSTRAINT membresia_id_socio_titular_fkey FOREIGN KEY (id_socio_titular)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_cuota
    ADD CONSTRAINT pago_cuota_id_cuota_fkey FOREIGN KEY (cuota_numero)
    REFERENCES public.cuota (id_cuota) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_evento
    ADD CONSTRAINT pago_evento_codigo_evento_fkey FOREIGN KEY (codigo_evento)
    REFERENCES public.evento (codigo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_reserva
    ADD CONSTRAINT pago_reserva_codigo_reserva_fkey FOREIGN KEY (codigo_reserva)
    REFERENCES public.reserva (codigo_reserva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT persona_codigo_comuna_fkey FOREIGN KEY (codigo_comuna)
    REFERENCES public.comuna (codigo_comuna) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_id_cargo_fkey FOREIGN KEY (id_cargo)
    REFERENCES public.cargo (id_cargo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.precio_lugar
    ADD CONSTRAINT precio_lugar_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relacion_socio
    ADD CONSTRAINT relacion_socio_id_socio_dependiente_fkey FOREIGN KEY (id_socio_dependiente)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relacion_socio
    ADD CONSTRAINT relacion_socio_id_socio_titular_fkey FOREIGN KEY (id_socio_titular)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT reserva_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT reserva_run_reservante_fkey FOREIGN KEY (run_reservante)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_codigo_sucursal_base_fkey FOREIGN KEY (codigo_sucursal_base)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sucursal
    ADD CONSTRAINT sucursal_codigo_comuna_fkey FOREIGN KEY (codigo_comuna)
    REFERENCES public.comuna (codigo_comuna) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;

-- termina DCColo.sql
-- ==============================================================================
-- CARGA Y MIGRACIÓN DE DATOS A LA BASE DE DATOS (VERSION PRINCIPIANTE)
-- ==============================================================================

-- 1. Crear Tablas Temporales para recibir los datos de los archivos CSV
-- En vez de usar funciones avanzadas o tipos complejos, usaremos VARCHAR para todo.
-- Luego, al pasar a las tablas definitivas, convertiremos los tipos de datos.

DROP TABLE IF EXISTS stg_regiones_comunas;
CREATE TEMP TABLE stg_regiones_comunas (
    codigo_comuna TEXT,
    nombre_comuna TEXT,
    codigo_region TEXT,
    nombre_region TEXT
);

DROP TABLE IF EXISTS stg_personas_socios;
CREATE TEMP TABLE stg_personas_socios (
    run_persona TEXT,
    nombre_completo TEXT,
    email TEXT,
    telefono_celular TEXT,
    telefono_alternativo TEXT,
    direccion_calle TEXT,
    comuna_nombre TEXT,
    region_codigo TEXT,
    region_nombre TEXT,
    tipo_persona TEXT,
    run_socio_titular TEXT,
    parentesco TEXT,
    fecha_nacimiento TEXT,
    fecha_inicio_membresia TEXT,
    fecha_fin_membresia TEXT,
    es_usuario_sistema TEXT,
    tipo_usuario TEXT,
    clave_en_texto_plano TEXT,
    sucursal_base_nombre TEXT
);

DROP TABLE IF EXISTS stg_sucursales_lugares;
CREATE TEMP TABLE stg_sucursales_lugares (
    sucursal_nombre TEXT,
    direccion_sucursal TEXT,
    comuna_nombre TEXT,
    lugar_nombre TEXT,
    tipo_lugar TEXT,
    capacidad_personas TEXT,
    precio TEXT,
    descuento_socio_evento TEXT,
    tipo_precio TEXT,
    dia_semana TEXT,
    hora_inicio TEXT,
    hora_termino TEXT,
    fecha_inicio_vigencia TEXT,
    fecha_fin_vigencia TEXT
);

DROP TABLE IF EXISTS stg_reservas_arriendos;
-- Agregamos una columna "id_temporal" auto-incremental (SERIAL) 
-- para poder identificar cada fila fácilmente sin usar comandos raros como "ctid"
CREATE TEMP TABLE stg_reservas_arriendos (
    id_temporal SERIAL,
    codigo_reserva TEXT,
    fecha_reserva TEXT,
    fecha_inicio TEXT,
    fecha_fin TEXT,
    estado_reserva TEXT,
    run_reservante TEXT,
    nombre_reservante TEXT,
    es_socio TEXT,
    lugar_nombre TEXT,
    sucursal_nombre TEXT,
    monto_total TEXT,
    monto_pagado TEXT,
    medio_pago TEXT,
    fecha_pago TEXT
);

DROP TABLE IF EXISTS stg_eventos;
CREATE TEMP TABLE stg_eventos (
    evento_id TEXT,
    nombre_evento TEXT,
    fecha_contratacion TEXT,
    fecha_evento TEXT,
    lugar_nombre TEXT,
    sucursal_nombre TEXT,
    tipo_cliente TEXT,
    run_cliente TEXT,
    nombre_cliente TEXT,
    rut_contacto_empresa TEXT,
    nombre_contacto_empresa TEXT,
    cargo_contacto TEXT,
    lista_asistentes TEXT,
    monto_total_evento TEXT,
    monto_pagado_reserva TEXT,
    monto_pagado_ejecucion TEXT
);

DROP TABLE IF EXISTS stg_pagos_membresias;
CREATE TEMP TABLE stg_pagos_membresias (
    pago_id TEXT,
    run_socio_titular TEXT,
    nombre_socio_titular TEXT,
    anio_membresia TEXT,
    mes_cuota TEXT,
    fecha_vencimiento TEXT,
    monto_membresia TEXT,
    monto_adicionales TEXT,
    monto_total TEXT,
    estado_pago TEXT,
    fecha_pago TEXT,
    medio_pago TEXT
);

DROP TABLE IF EXISTS stg_cargos_administrativos;
CREATE TEMP TABLE stg_cargos_administrativos (
    run_persona TEXT,
    sucursal_nombre TEXT,
    nombre_cargo TEXT,
    fecha_inicio_cargo TEXT,
    fecha_termino_cargo TEXT
);

-- Tablas para guardar registro de errores y operaciones exitosas
DROP TABLE IF EXISTS temp_carga_err;
CREATE TEMP TABLE temp_carga_err (
    tupla TEXT,
    motivo TEXT
);

DROP TABLE IF EXISTS temp_carga_log;
CREATE TEMP TABLE temp_carga_log (
    accion TEXT,
    detalle TEXT
);

-- 2. Cargar datos desde los archivos CSV a las tablas temporales
-- Utilizamos \copy que es el comando estándar para importar CSV
\copy stg_regiones_comunas FROM 'regiones_comunas.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_personas_socios FROM 'data_ok/personas_sociosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_sucursales_lugares FROM 'data_ok/sucursales_lugaresOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_reservas_arriendos (codigo_reserva, fecha_reserva, fecha_inicio, fecha_fin, estado_reserva, run_reservante, nombre_reservante, es_socio, lugar_nombre, sucursal_nombre, monto_total, monto_pagado, medio_pago, fecha_pago) FROM 'data_ok/reservas_arriendosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_eventos FROM 'data_ok/eventosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_pagos_membresias FROM 'data_ok/pagos_membresiasOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_cargos_administrativos FROM 'data_ok/cargos_administrativosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';


-- ==============================================================================
-- 3. INSERCIÓN DE DATOS EN TABLAS DEFINITIVAS
-- ==============================================================================
-- Lo haremos paso a paso. Usaremos subconsultas con "NOT EXISTS" en lugar de 
-- "ON CONFLICT DO NOTHING" porque es más fácil de entender cómo funciona: 
-- "Inserta este dato solo si no existe ya en la tabla".

-- 3.1. Regiones
INSERT INTO public.region (codigo_region, nombre)
SELECT 
    CAST(codigo_region AS integer), 
    nombre_region
FROM stg_regiones_comunas
WHERE codigo_region IS NOT NULL 
  AND codigo_region != ''
  -- Evitamos insertar duplicados verificando que no exista ya en la tabla final
  AND NOT EXISTS (
      SELECT 1 FROM public.region WHERE public.region.codigo_region = CAST(stg_regiones_comunas.codigo_region AS integer)
  )
GROUP BY codigo_region, nombre_region;

-- 3.2. Comunas
INSERT INTO public.comuna (codigo_comuna, nombre, codigo_region)
SELECT 
    CAST(codigo_comuna AS integer), 
    nombre_comuna, 
    CAST(codigo_region AS integer)
FROM stg_regiones_comunas
WHERE codigo_comuna IS NOT NULL 
  AND codigo_comuna != ''
  AND codigo_region IS NOT NULL 
  AND codigo_region != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.comuna WHERE public.comuna.codigo_comuna = CAST(stg_regiones_comunas.codigo_comuna AS integer)
  )
GROUP BY codigo_comuna, nombre_comuna, codigo_region;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron regiones y comunas');

-- 3.3. Sucursales
-- Para crear el código de la sucursal usaremos UPPER y LEFT para tomar los primeros 10 caracteres
INSERT INTO public.sucursal (codigo_sucursal, nombre, direccion, codigo_comuna)
SELECT 
    LEFT(REPLACE(UPPER(s.sucursal_nombre), ' ', ''), 10),
    s.sucursal_nombre,
    s.direccion_sucursal,
    CAST(c.codigo_comuna AS integer)
FROM stg_sucursales_lugares s
-- Hacemos JOIN con la tabla temporal de comunas para obtener el código
-- Usamos REPLACE para quitar los tildes más comunes y UPPER para comparar en mayúsculas
LEFT JOIN stg_regiones_comunas c 
    ON REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(c.nombre_comuna), 'Á', 'A'), 'É', 'E'), 'Í', 'I'), 'Ó', 'O'), 'Ú', 'U') = 
       REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(s.comuna_nombre), 'Á', 'A'), 'É', 'E'), 'Í', 'I'), 'Ó', 'O'), 'Ú', 'U')
WHERE s.sucursal_nombre IS NOT NULL 
  AND s.sucursal_nombre != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.sucursal WHERE public.sucursal.codigo_sucursal = LEFT(REPLACE(UPPER(s.sucursal_nombre), ' ', ''), 10)
  )
GROUP BY s.sucursal_nombre, s.direccion_sucursal, c.codigo_comuna;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron sucursales');

-- Guardamos registro de las sucursales a las que no se les encontró comuna
INSERT INTO temp_carga_err (tupla, motivo)
SELECT s.sucursal_nombre, 'Comuna no encontrada para sucursal'
FROM stg_sucursales_lugares s
LEFT JOIN stg_regiones_comunas c 
    ON REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(c.nombre_comuna), 'Á', 'A'), 'É', 'E'), 'Í', 'I'), 'Ó', 'O'), 'Ú', 'U') = 
       REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(s.comuna_nombre), 'Á', 'A'), 'É', 'E'), 'Í', 'I'), 'Ó', 'O'), 'Ú', 'U')
WHERE c.codigo_comuna IS NULL
GROUP BY s.sucursal_nombre;

-- 3.4. Lugares
INSERT INTO public.lugar (codigo_lugar, nombre, capacidad, codigo_sucursal, tipo_lugar)
SELECT 
    LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15),
    MAX(lugar_nombre),
    MAX(CAST(capacidad_personas AS integer)),
    MAX(LEFT(REPLACE(UPPER(sucursal_nombre), ' ', ''), 10)),
    MAX(tipo_lugar)
FROM stg_sucursales_lugares
WHERE lugar_nombre IS NOT NULL AND lugar_nombre != ''
  AND capacidad_personas != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.lugar WHERE public.lugar.codigo_lugar = LEFT(REPLACE(UPPER(stg_sucursales_lugares.sucursal_nombre || '_' || stg_sucursales_lugares.lugar_nombre), ' ', ''), 15)
  )
GROUP BY LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15);

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron lugares');

-- 3.5. Precio Lugares
INSERT INTO public.precio_lugar (codigo_lugar, tipo_precio, dia_semana, hora_inicio, hora_termino, fecha_inicio, fecha_fin, monto)
SELECT 
    LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15),
    tipo_precio,
    dia_semana,
    CAST(hora_inicio AS time),
    CAST(hora_termino AS time),
    CAST(fecha_inicio_vigencia AS date),
    CAST(fecha_fin_vigencia AS date),
    CAST(precio AS integer)
FROM stg_sucursales_lugares
WHERE precio IS NOT NULL AND precio != ''
  AND hora_inicio != '' AND hora_termino != ''
  AND fecha_inicio_vigencia != '' AND fecha_fin_vigencia != ''
  AND lugar_nombre IS NOT NULL AND lugar_nombre != '';

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron precios de lugares');

-- 3.6. Personas
INSERT INTO public.persona (run, nombre_completo, email, telefono_celular, telefono_alternativo, direccion_calle, codigo_comuna, fecha_nacimiento)
SELECT 
    s.run_persona,
    MAX(s.nombre_completo),
    MAX(s.email),
    MAX(s.telefono_celular),
    MAX(s.telefono_alternativo),
    MAX(s.direccion_calle),
    MAX(CAST(c.codigo_comuna AS integer)),
    MAX(CAST(s.fecha_nacimiento AS date))
FROM stg_personas_socios s
LEFT JOIN stg_regiones_comunas c 
    ON REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(c.nombre_comuna), 'Á', 'A'), 'É', 'E'), 'Í', 'I'), 'Ó', 'O'), 'Ú', 'U') = 
       REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(s.comuna_nombre), 'Á', 'A'), 'É', 'E'), 'Í', 'I'), 'Ó', 'O'), 'Ú', 'U')
WHERE s.run_persona IS NOT NULL AND s.run_persona != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.persona WHERE public.persona.run = s.run_persona
  )
GROUP BY s.run_persona;

-- Agregamos las personas que vienen de reservas y que no estaban
INSERT INTO public.persona (run, nombre_completo)
SELECT run_reservante, MAX(nombre_reservante)
FROM stg_reservas_arriendos
WHERE run_reservante IS NOT NULL AND run_reservante != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.persona WHERE public.persona.run = stg_reservas_arriendos.run_reservante
  )
GROUP BY run_reservante;

-- Agregamos las personas que vienen de eventos (clientes personas)
INSERT INTO public.persona (run, nombre_completo)
SELECT run_cliente, MAX(nombre_cliente)
FROM stg_eventos
WHERE tipo_cliente = 'persona' 
  AND run_cliente IS NOT NULL AND run_cliente != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.persona WHERE public.persona.run = stg_eventos.run_cliente
  )
GROUP BY run_cliente;

-- Agregamos las personas que son contacto de una empresa
INSERT INTO public.persona (run, nombre_completo)
SELECT rut_contacto_empresa, MAX(nombre_contacto_empresa)
FROM stg_eventos
WHERE tipo_cliente = 'empresa-institucion' 
  AND rut_contacto_empresa IS NOT NULL AND rut_contacto_empresa != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.persona WHERE public.persona.run = stg_eventos.rut_contacto_empresa
  )
GROUP BY rut_contacto_empresa;

-- Tabla NACI (Mantiene el historial o información de nacimientos)
INSERT INTO public.naci (run, nac)
SELECT run_persona, CAST(fecha_nacimiento AS date)
FROM stg_personas_socios
WHERE run_persona IS NOT NULL AND run_persona != '' 
  AND fecha_nacimiento IS NOT NULL AND fecha_nacimiento != ''
GROUP BY run_persona, fecha_nacimiento;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron personas');

-- 3.7. Socios
INSERT INTO public.socio (run_persona, tipo_socio, fecha_inicio, fecha_fin, codigo_sucursal_base)
SELECT 
    run_persona,
    tipo_persona,
    CAST(fecha_inicio_membresia AS date),
    -- Usamos CASE para validar si la fecha_fin_membresia viene vacía, si es así guardamos NULL
    CASE WHEN fecha_fin_membresia = '' THEN NULL ELSE CAST(fecha_fin_membresia AS date) END,
    LEFT(REPLACE(UPPER(sucursal_base_nombre), ' ', ''), 10)
FROM stg_personas_socios
WHERE run_persona IS NOT NULL 
  AND tipo_persona IN ('socio_titular', 'adicional', 'beneficiario', 'invitado') 
  -- Aseguramos que la persona ya exista en la tabla persona
  AND run_persona IN (SELECT run FROM public.persona)
  AND NOT EXISTS (
      SELECT 1 FROM public.socio WHERE public.socio.run_persona = stg_personas_socios.run_persona
  )
GROUP BY run_persona, tipo_persona, fecha_inicio_membresia, fecha_fin_membresia, sucursal_base_nombre;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron socios');

-- 3.8. Membresía
INSERT INTO public.membresia (id_socio, id_socio_titular, anio, fecha_inicio, fecha_fin, monto_base)
SELECT 
    so.id_socio, 
    so.id_socio, 
    -- Extraemos el año de la fecha usando la función EXTRACT
    CAST(EXTRACT(YEAR FROM CAST(stg.fecha_inicio_membresia AS date)) AS integer), 
    CAST(stg.fecha_inicio_membresia AS date), 
    CASE WHEN stg.fecha_fin_membresia = '' THEN NULL ELSE CAST(stg.fecha_fin_membresia AS date) END, 
    0
FROM stg_personas_socios stg
JOIN public.socio so ON stg.run_persona = so.run_persona
WHERE stg.tipo_persona = 'socio_titular'
  AND NOT EXISTS (
      SELECT 1 FROM public.membresia WHERE public.membresia.id_socio = so.id_socio
  );

-- 3.9. Usuarios
INSERT INTO public.usuario (run_persona, email_login, clave_encriptada, tipo_usuario)
SELECT 
    run_persona,
    email,
    clave_en_texto_plano,
    tipo_usuario
FROM stg_personas_socios
WHERE es_usuario_sistema = 'SI' 
  AND clave_en_texto_plano IS NOT NULL AND clave_en_texto_plano != '' 
  AND run_persona IN (SELECT run FROM public.persona)
  AND NOT EXISTS (
      SELECT 1 FROM public.usuario WHERE public.usuario.run_persona = stg_personas_socios.run_persona
  )
GROUP BY run_persona, email, clave_en_texto_plano, tipo_usuario;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron usuarios y membresias');

-- 3.10. Relación entre Socios (titular y dependientes)
INSERT INTO public.relacion_socio (id_socio_titular, id_socio_dependiente, parentesco)
SELECT 
    s_titular.id_socio,
    s_dep.id_socio,
    stg.parentesco
FROM stg_personas_socios stg
JOIN public.socio s_dep ON s_dep.run_persona = stg.run_persona
JOIN public.socio s_titular ON s_titular.run_persona = stg.run_socio_titular
WHERE stg.tipo_persona IN ('adicional', 'beneficiario', 'invitado') 
  AND stg.run_socio_titular IS NOT NULL AND stg.run_socio_titular != '';

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron relaciones de socios');

-- 3.11. Empresa
INSERT INTO public.empresa (rut_empresa, nombre)
SELECT 
    run_cliente, 
    nombre_cliente
FROM stg_eventos
WHERE tipo_cliente = 'empresa-institucion' 
  AND run_cliente IS NOT NULL AND run_cliente != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.empresa WHERE public.empresa.rut_empresa = stg_eventos.run_cliente
  )
GROUP BY run_cliente, nombre_cliente;

-- 3.12. Contacto Empresa
INSERT INTO public.contacto_empresa (rut_empresa, run_persona, nombre, cargo)
SELECT 
    run_cliente, 
    rut_contacto_empresa, 
    nombre_contacto_empresa, 
    cargo_contacto
FROM stg_eventos
WHERE tipo_cliente = 'empresa-institucion' 
  AND run_cliente IS NOT NULL AND run_cliente != ''
  AND rut_contacto_empresa IN (SELECT run FROM public.persona)
  AND NOT EXISTS (
      SELECT 1 FROM public.contacto_empresa 
      WHERE public.contacto_empresa.rut_empresa = stg_eventos.run_cliente 
        AND public.contacto_empresa.run_persona = stg_eventos.rut_contacto_empresa
  )
GROUP BY run_cliente, rut_contacto_empresa, nombre_contacto_empresa, cargo_contacto;

-- 3.13. Eventos
INSERT INTO public.evento (codigo_evento, nombre, fecha_evento, codigo_lugar, codigo_sucursal, tipo_cliente, identificador_cliente)
SELECT 
    evento_id,
    nombre_evento,
    CAST(fecha_evento AS date),
    LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15),
    LEFT(REPLACE(UPPER(sucursal_nombre), ' ', ''), 10),
    tipo_cliente,
    run_cliente
FROM stg_eventos
WHERE evento_id IS NOT NULL AND evento_id != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.evento WHERE public.evento.codigo_evento = stg_eventos.evento_id
  )
GROUP BY evento_id, nombre_evento, fecha_evento, sucursal_nombre, lugar_nombre, tipo_cliente, run_cliente;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron eventos y empresas');

-- 3.14. Asistentes a Eventos
-- Aquí usamos string_to_array y unnest porque es la única forma estándar en PostgreSQL 
-- para separar una lista de valores separados por coma o punto y coma en varias filas.
INSERT INTO public.asistente_evento (codigo_evento, nombre_asistente)
SELECT 
    evento_id,
    unnest(string_to_array(lista_asistentes, ';'))
FROM stg_eventos
WHERE lista_asistentes IS NOT NULL AND lista_asistentes != '';

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron asistentes de eventos');

-- 3.15. Pagos de Eventos (Reservas y Ejecución)
INSERT INTO public.pago_evento (codigo_evento, fecha_pago, monto, tipo_pago)
SELECT 
    evento_id,
    CAST(fecha_contratacion AS date), 
    CAST(monto_pagado_reserva AS integer),
    'RESERVA'
FROM stg_eventos
WHERE monto_pagado_reserva != '' AND monto_pagado_reserva != '0';

INSERT INTO public.pago_evento (codigo_evento, fecha_pago, monto, tipo_pago)
SELECT 
    evento_id,
    CAST(fecha_evento AS date), 
    CAST(monto_pagado_ejecucion AS integer),
    'EJECUCION'
FROM stg_eventos
WHERE monto_pagado_ejecucion != '' AND monto_pagado_ejecucion != '0';

-- 3.16. Reservas y Arriendos
-- Si el código de reserva viene en blanco, lo generamos concatenando 'RES-' con nuestro id_temporal
UPDATE stg_reservas_arriendos
SET codigo_reserva = 'RES-' || CAST(id_temporal AS VARCHAR)
WHERE codigo_reserva IS NULL OR codigo_reserva = '';

INSERT INTO public.reserva (codigo_reserva, codigo_lugar, run_reservante, fecha_inicio, fecha_fin, estado)
SELECT 
    r.codigo_reserva,
    l.codigo_lugar,
    r.run_reservante,
    -- Si la fecha viene mala (como 2025-02-31 o 2025-05-00) la corregimos, si no tiene la ponemos por defecto
    CASE 
        WHEN r.fecha_inicio = '2025-02-31' THEN CAST('2025-02-28 00:00:00' AS timestamp) 
        WHEN r.fecha_inicio = '2025-05-00' THEN CAST('2025-05-01 00:00:00' AS timestamp)
        WHEN r.fecha_inicio = '2025-12-abc' THEN CAST('2025-12-01 00:00:00' AS timestamp)
        WHEN r.fecha_inicio = '2025-00-15' THEN CAST('2025-01-15 00:00:00' AS timestamp)
        WHEN r.fecha_inicio != '' THEN CAST(r.fecha_inicio AS timestamp) 
        ELSE CAST('1900-01-01 00:00:00' AS timestamp) 
    END,
    CASE 
        WHEN r.fecha_fin = '2025-02-31' THEN CAST('2025-02-28 00:00:00' AS timestamp) 
        WHEN r.fecha_fin = '2025-05-00' THEN CAST('2025-05-01 00:00:00' AS timestamp)
        WHEN r.fecha_fin = '2025-12-abc' THEN CAST('2025-12-01 00:00:00' AS timestamp)
        WHEN r.fecha_fin = '2025-00-15' THEN CAST('2025-01-15 00:00:00' AS timestamp)
        WHEN r.fecha_fin != '' THEN CAST(r.fecha_fin AS timestamp) 
        ELSE CAST('1900-01-01 00:00:00' AS timestamp) 
    END,
    r.estado_reserva
FROM stg_reservas_arriendos r
LEFT JOIN public.lugar l ON l.codigo_lugar = LEFT(REPLACE(UPPER(r.sucursal_nombre || '_' || r.lugar_nombre), ' ', ''), 15)
WHERE r.codigo_reserva IS NOT NULL AND r.codigo_reserva != ''
  AND r.run_reservante IN (SELECT run FROM public.persona)
  AND NOT EXISTS (
      SELECT 1 FROM public.reserva WHERE public.reserva.codigo_reserva = r.codigo_reserva
  )
GROUP BY r.codigo_reserva, l.codigo_lugar, r.run_reservante, r.fecha_inicio, r.fecha_fin, r.estado_reserva;

INSERT INTO public.pago_reserva (codigo_reserva, fecha_pago, monto, medio_pago)
SELECT 
    codigo_reserva,
    CASE 
        WHEN fecha_pago = '2025-02-31' THEN CAST('2025-02-28' AS date) 
        WHEN fecha_pago = '2025-05-00' THEN CAST('2025-05-01' AS date) 
        WHEN fecha_pago = '2025-12-abc' THEN CAST('2025-12-01' AS date) 
        WHEN fecha_pago = '2025-00-15' THEN CAST('2025-01-15' AS date) 
        ELSE CAST(fecha_pago AS date) 
    END,
    CAST(monto_pagado AS integer),
    medio_pago
FROM stg_reservas_arriendos
WHERE monto_pagado != '' AND monto_pagado != '0'
  AND codigo_reserva IN (SELECT codigo_reserva FROM public.reserva);

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron reservas y pagos_reserva');

-- 3.17. Cuota y Pago Membresía
INSERT INTO public.cuota (id_membresia, mes, fecha_vencimiento, monto_total, estado)
SELECT 
    m.id_socio, 
    CAST(stg.mes_cuota AS integer),
    CASE 
        WHEN stg.fecha_vencimiento = '2025-02-31' THEN CAST('2025-02-28' AS date) 
        WHEN stg.fecha_vencimiento = '2025-05-00' THEN CAST('2025-05-01' AS date) 
        WHEN stg.fecha_vencimiento = '2025-12-abc' THEN CAST('2025-12-01' AS date) 
        WHEN stg.fecha_vencimiento = '2025-00-15' THEN CAST('2025-01-15' AS date) 
        ELSE CAST(stg.fecha_vencimiento AS date) 
    END,
    CAST(stg.monto_total AS integer),
    stg.estado_pago
FROM stg_pagos_membresias stg
JOIN public.socio s ON s.run_persona = stg.run_socio_titular
JOIN public.membresia m ON m.id_socio = s.id_socio
WHERE stg.mes_cuota != '' AND stg.monto_total != ''
GROUP BY m.id_socio, stg.mes_cuota, stg.fecha_vencimiento, stg.monto_total, stg.estado_pago;

INSERT INTO public.pago_cuota (cuota_numero, fecha_pago, monto_pagado, medio_pago, id_socio)
SELECT 
    c.id_cuota,
    CAST(stg.fecha_pago AS date), -- Aquí reemplazamos todo el CASE
    CAST(stg.monto_total AS integer),
    stg.medio_pago,
    s.id_socio
FROM stg_pagos_membresias stg
JOIN public.socio s ON s.run_persona = stg.run_socio_titular
JOIN public.membresia m ON m.id_socio = s.id_socio
JOIN public.cuota c ON c.id_membresia = m.id_socio AND c.mes = CAST(stg.mes_cuota AS integer)
WHERE stg.fecha_pago IS NOT NULL AND stg.fecha_pago != ''
GROUP BY c.id_cuota, stg.fecha_pago, stg.monto_total, stg.medio_pago, s.id_socio;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron cuotas y pagos de membresia');

-- 3.18. Cargos y Persona Cargo
INSERT INTO public.cargo (nombre)
SELECT nombre_cargo
FROM stg_cargos_administrativos
WHERE nombre_cargo IS NOT NULL AND nombre_cargo != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.cargo WHERE public.cargo.nombre = stg_cargos_administrativos.nombre_cargo
  )
GROUP BY nombre_cargo;

INSERT INTO public.persona_cargo (run_persona, id_cargo, codigo_sucursal, fecha_inicio, fecha_termino)
SELECT 
    stg.run_persona,
    c.id_cargo,
    LEFT(REPLACE(UPPER(stg.sucursal_nombre), ' ', ''), 10),
    CAST(stg.fecha_inicio_cargo AS date),
    CASE WHEN stg.fecha_termino_cargo != '' THEN CAST(stg.fecha_termino_cargo AS date) ELSE NULL END
FROM stg_cargos_administrativos stg
JOIN public.cargo c ON c.nombre = stg.nombre_cargo
WHERE stg.run_persona IS NOT NULL AND stg.run_persona != '' 
  AND stg.run_persona IN (SELECT run FROM public.persona) 
  AND LEFT(REPLACE(UPPER(stg.sucursal_nombre), ' ', ''), 10) IN (SELECT codigo_sucursal FROM public.sucursal)
GROUP BY stg.run_persona, c.id_cargo, stg.sucursal_nombre, stg.fecha_inicio_cargo, stg.fecha_termino_cargo;

INSERT INTO temp_carga_log (accion, detalle) VALUES ('INSERCION EXITOSA', 'Se cargaron cargos y persona_cargo');

-- 4. Validar integridad final y poblar tabla de errores
INSERT INTO temp_carga_err (tupla, motivo)
SELECT run_persona, 'RUN en cargos administrativos que no existe en personas'
FROM stg_cargos_administrativos
WHERE run_persona NOT IN (SELECT run FROM public.persona);

-- 5. Generar los archivos finales con el log y errores
\copy temp_carga_err TO 'cargaERR.csv' WITH CSV HEADER DELIMITER ';';
\copy temp_carga_log TO 'cargaLOG.txt' WITH CSV HEADER DELIMITER ';';

-- FIN DEL SCRIPT
