--limpiamos base de datos pq a veces da problemas
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- pegamos DCColo.sql

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asistente_evento
(
    id_asistente serial NOT NULL,
    codigo_evento character varying(20) COLLATE pg_catalog."default",
    run_asistente character varying(12) COLLATE pg_catalog."default",
    nombre_asistente character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT asistente_evento_pkey PRIMARY KEY (id_asistente)
);

CREATE TABLE IF NOT EXISTS public.cargo
(
    id_cargo serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cargo_pkey PRIMARY KEY (id_cargo)
);

CREATE TABLE IF NOT EXISTS public.comuna
(
    codigo_comuna integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigo_region integer NOT NULL,
    CONSTRAINT comuna_pkey PRIMARY KEY (codigo_comuna)
);

CREATE TABLE IF NOT EXISTS public.contacto_empresa
(
    id_contacto serial NOT NULL,
    rut_empresa character varying(15) COLLATE pg_catalog."default",
    run_persona character varying(12) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default",
    cargo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT contacto_empresa_pkey PRIMARY KEY (id_contacto)
);

CREATE TABLE IF NOT EXISTS public.cuota
(
    id_cuota serial NOT NULL,
    id_membresia integer,
    mes integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    monto_total integer NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cuota_pkey PRIMARY KEY (id_cuota)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    rut_empresa character varying(15) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT empresa_pkey PRIMARY KEY (rut_empresa)
);

CREATE TABLE IF NOT EXISTS public.evento
(
    codigo_evento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    fecha_evento date NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    codigo_sucursal character varying(10) COLLATE pg_catalog."default",
    tipo_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    identificador_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT evento_pkey PRIMARY KEY (codigo_evento)
);

CREATE TABLE IF NOT EXISTS public.lugar
(
    codigo_lugar character varying(15) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    capacidad integer NOT NULL,
    codigo_sucursal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tipo_lugar character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT lugar_pkey PRIMARY KEY (codigo_lugar)
);

CREATE TABLE IF NOT EXISTS public.membresia
(
    id_socio integer NOT NULL,
    id_socio_titular integer,
    anio integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    monto_base integer NOT NULL,
    CONSTRAINT membresia_pkey PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.naci
(
    run character varying(12) COLLATE pg_catalog."default",
    nac date
);

CREATE TABLE IF NOT EXISTS public.pago_cuota
(
    id_pago_cuota serial NOT NULL,
    cuota_numero integer,
    fecha_pago date NOT NULL,
    monto_pagado integer NOT NULL,
    medio_pago character varying(30) COLLATE pg_catalog."default",
    id_socio integer,
    CONSTRAINT pago_cuota_pkey PRIMARY KEY (id_pago_cuota)
);

CREATE TABLE IF NOT EXISTS public.pago_evento
(
    id_pago_evento serial NOT NULL,
    codigo_evento character varying(20) COLLATE pg_catalog."default",
    fecha_pago date NOT NULL,
    monto integer NOT NULL,
    tipo_pago character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pago_evento_pkey PRIMARY KEY (id_pago_evento)
);

CREATE TABLE IF NOT EXISTS public.pago_reserva
(
    id_pago_reserva serial NOT NULL,
    codigo_reserva character varying(20) COLLATE pg_catalog."default",
    fecha_pago date NOT NULL,
    monto integer NOT NULL,
    medio_pago character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT pago_reserva_pkey PRIMARY KEY (id_pago_reserva)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    run character varying(12) COLLATE pg_catalog."default" NOT NULL,
    nombre_completo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default",
    telefono_celular character varying(20) COLLATE pg_catalog."default",
    telefono_alternativo character varying(20) COLLATE pg_catalog."default",
    direccion_calle character varying(150) COLLATE pg_catalog."default",
    codigo_comuna integer,
    fecha_nacimiento date,
    CONSTRAINT persona_pkey PRIMARY KEY (run)
);

CREATE TABLE IF NOT EXISTS public.persona_cargo
(
    id_persona_cargo serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    id_cargo integer,
    codigo_sucursal character varying(10) COLLATE pg_catalog."default",
    fecha_inicio date NOT NULL,
    fecha_termino date,
    CONSTRAINT persona_cargo_pkey PRIMARY KEY (id_persona_cargo)
);

CREATE TABLE IF NOT EXISTS public.precio_lugar
(
    id_precio serial NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    tipo_precio character varying(10) COLLATE pg_catalog."default" NOT NULL,
    dia_semana character varying(15) COLLATE pg_catalog."default",
    hora_inicio time without time zone,
    hora_termino time without time zone,
    fecha_inicio date,
    fecha_fin date,
    monto integer NOT NULL,
    CONSTRAINT precio_lugar_pkey PRIMARY KEY (id_precio)
);

CREATE TABLE IF NOT EXISTS public.region
(
    codigo_region integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (codigo_region)
);

CREATE TABLE IF NOT EXISTS public.relacion_socio
(
    id_relacion serial NOT NULL,
    id_socio_titular integer,
    id_socio_dependiente integer,
    parentesco character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT relacion_socio_pkey PRIMARY KEY (id_relacion)
);

CREATE TABLE IF NOT EXISTS public.reserva
(
    codigo_reserva character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codigo_lugar character varying(15) COLLATE pg_catalog."default",
    run_reservante character varying(12) COLLATE pg_catalog."default",
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT reserva_pkey PRIMARY KEY (codigo_reserva)
);

CREATE TABLE IF NOT EXISTS public.socio
(
    id_socio serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    tipo_socio character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    codigo_sucursal_base character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT socio_pkey PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.sucursal
(
    codigo_sucursal character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    codigo_comuna integer,
    CONSTRAINT sucursal_pkey PRIMARY KEY (codigo_sucursal)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    run_persona character varying(12) COLLATE pg_catalog."default",
    email_login character varying(150) COLLATE pg_catalog."default" NOT NULL,
    clave_encriptada character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_usuario character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.asistente_evento
    ADD CONSTRAINT asistente_evento_codigo_evento_fkey FOREIGN KEY (codigo_evento)
    REFERENCES public.evento (codigo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comuna
    ADD CONSTRAINT comuna_codigo_region_fkey FOREIGN KEY (codigo_region)
    REFERENCES public.region (codigo_region) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contacto_empresa
    ADD CONSTRAINT contacto_empresa_rut_empresa_fkey FOREIGN KEY (rut_empresa)
    REFERENCES public.empresa (rut_empresa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cuota
    ADD CONSTRAINT cuota_id_membresia_fkey FOREIGN KEY (id_membresia)
    REFERENCES public.membresia (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lugar
    ADD CONSTRAINT lugar_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.membresia
    ADD CONSTRAINT membresia_id_socio_titular_fkey FOREIGN KEY (id_socio_titular)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_cuota
    ADD CONSTRAINT pago_cuota_id_cuota_fkey FOREIGN KEY (cuota_numero)
    REFERENCES public.cuota (id_cuota) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_evento
    ADD CONSTRAINT pago_evento_codigo_evento_fkey FOREIGN KEY (codigo_evento)
    REFERENCES public.evento (codigo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago_reserva
    ADD CONSTRAINT pago_reserva_codigo_reserva_fkey FOREIGN KEY (codigo_reserva)
    REFERENCES public.reserva (codigo_reserva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT persona_codigo_comuna_fkey FOREIGN KEY (codigo_comuna)
    REFERENCES public.comuna (codigo_comuna) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_codigo_sucursal_fkey FOREIGN KEY (codigo_sucursal)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_id_cargo_fkey FOREIGN KEY (id_cargo)
    REFERENCES public.cargo (id_cargo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persona_cargo
    ADD CONSTRAINT persona_cargo_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.precio_lugar
    ADD CONSTRAINT precio_lugar_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relacion_socio
    ADD CONSTRAINT relacion_socio_id_socio_dependiente_fkey FOREIGN KEY (id_socio_dependiente)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relacion_socio
    ADD CONSTRAINT relacion_socio_id_socio_titular_fkey FOREIGN KEY (id_socio_titular)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT reserva_codigo_lugar_fkey FOREIGN KEY (codigo_lugar)
    REFERENCES public.lugar (codigo_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT reserva_run_reservante_fkey FOREIGN KEY (run_reservante)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_codigo_sucursal_base_fkey FOREIGN KEY (codigo_sucursal_base)
    REFERENCES public.sucursal (codigo_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sucursal
    ADD CONSTRAINT sucursal_codigo_comuna_fkey FOREIGN KEY (codigo_comuna)
    REFERENCES public.comuna (codigo_comuna) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_run_persona_fkey FOREIGN KEY (run_persona)
    REFERENCES public.persona (run) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


-- termina DCColo.sql



-- creamos las tablas temporales para asegurarnos de cargar bien los datos y q nno hayan errores al poblar las tablas

CREATE TEMP TABLE stg_regiones_comunas (id_comuna TEXT, nombre_comuna TEXT, id_region TEXT, nombre_region TEXT);
CREATE TEMP TABLE stg_personas_socios (run_persona TEXT, nombre_completo TEXT, email TEXT, telefono_celular TEXT, telefono_alternativo TEXT, direccion_calle TEXT, comuna_nombre TEXT, region_codigo TEXT, region_nombre TEXT, tipo_persona TEXT, run_socio_titular TEXT, parentesco TEXT, fecha_nacimiento TEXT, fecha_inicio_membresia TEXT, fecha_fin_membresia TEXT, es_usuario_sistema TEXT, tipo_usuario TEXT, clave_en_texto_plano TEXT, sucursal_base_nombre TEXT);
CREATE TEMP TABLE stg_sucursales_lugares (sucursal_nombre TEXT, direccion_sucursal TEXT, comuna_nombre TEXT, lugar_nombre TEXT, tipo_lugar TEXT, capacidad_personas TEXT, precio TEXT, descuento_socio_evento TEXT, tipo_precio TEXT, dia_semana TEXT, hora_inicio TEXT, hora_termino TEXT, fecha_inicio_vigencia TEXT, fecha_fin_vigencia TEXT);
CREATE TEMP TABLE stg_eventos (evento_id TEXT, nombre_evento TEXT, fecha_contratacion TEXT, fecha_evento TEXT, lugar_nombre TEXT, sucursal_nombre TEXT, tipo_cliente TEXT, run_cliente TEXT, nombre_cliente TEXT, rut_contacto_empresa TEXT, nombre_contacto_empresa TEXT, cargo_contacto TEXT, lista_asistentes TEXT, monto_total_evento TEXT, monto_pagado_reserva TEXT, monto_pagado_ejecucion TEXT);
CREATE TEMP TABLE stg_pagos_membresias (pago_id TEXT, run_socio_titular TEXT, nombre_socio_titular TEXT, anio_membresia TEXT, mes_cuota TEXT, fecha_vencimiento TEXT, monto_membresia TEXT, monto_adicionales TEXT, monto_total TEXT, estado_pago TEXT, fecha_pago TEXT, medio_pago TEXT);
CREATE TEMP TABLE stg_cargos_administrativos (run_persona TEXT, sucursal_nombre TEXT, nombre_cargo TEXT, fecha_inicio_cargo TEXT, fecha_termino_cargo TEXT);

--  Añadimos id_temporal SERIAL para generar codigos de reserva 

CREATE TEMP TABLE stg_reservas_arriendos (id_temporal SERIAL, codigo_reserva TEXT, fecha_reserva TEXT, fecha_inicio TEXT, fecha_fin TEXT, estado_reserva TEXT, run_reservante TEXT, nombre_reservante TEXT, es_socio TEXT, lugar_nombre TEXT, sucursal_nombre TEXT, monto_total TEXT, monto_pagado TEXT, medio_pago TEXT, fecha_pago TEXT);

-- cargamos los datos 

\copy stg_regiones_comunas FROM 'regiones_comunas/regiones_comunas.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_personas_socios FROM 'personas_socios/personas_sociosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_sucursales_lugares FROM 'sucursales_lugares/sucursales_lugaresOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_eventos FROM 'eventos/eventosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_pagos_membresias FROM 'pagos_membresias/pagos_membresiasOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';
\copy stg_cargos_administrativos FROM 'cargos_administrativos/cargos_administrativosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';

-- copiamos reservas_arriendos de esta forma poder añadir id unicos ya que codigos_reservas estan vacios

\copy stg_reservas_arriendos (codigo_reserva, fecha_reserva, fecha_inicio, fecha_fin, estado_reserva, run_reservante, nombre_reservante, es_socio, lugar_nombre, sucursal_nombre, monto_total, monto_pagado, medio_pago, fecha_pago) FROM 'reservas_arriendos/reservas_arriendosOK.csv' WITH CSV HEADER DELIMITER ';' ENCODING 'UTF8';


-- hacemos la poblacion de datos 

-- de Regiones
INSERT INTO region (codigo_region, nombre)
SELECT DISTINCT 
    CAST(id_region AS INTEGER), 
    TRIM(UPPER(nombre_region))
FROM stg_regiones_comunas 
WHERE id_region IS NOT NULL 
  AND id_region != '' 
ON CONFLICT DO NOTHING;

-- de Comunas
INSERT INTO comuna (codigo_comuna, nombre, codigo_region)
SELECT DISTINCT 
    CAST(id_comuna AS INTEGER), 
    TRIM(UPPER(nombre_comuna)), 
    CAST(id_region AS INTEGER)
FROM stg_regiones_comunas 
WHERE id_comuna IS NOT NULL 
  AND id_comuna != '' 
ON CONFLICT DO NOTHING;

-- de Sucursales 
INSERT INTO sucursal (
    codigo_sucursal, 
    nombre, 
    direccion, 
    codigo_comuna
)
SELECT 
    LEFT(REPLACE(UPPER(s.sucursal_nombre), ' ', ''), 10), 
    s.sucursal_nombre, 
    s.direccion_sucursal, 
    CAST(c.id_comuna AS integer)
FROM stg_sucursales_lugares s
LEFT JOIN stg_regiones_comunas c 
    ON TRIM(UPPER(c.nombre_comuna)) = TRIM(UPPER(s.comuna_nombre))
WHERE s.sucursal_nombre IS NOT NULL 
  AND s.sucursal_nombre != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM sucursal 
      -- hacemos el codigo como la sucursal pero de maximo 10 caracteres pq es varchar(10)
      WHERE sucursal.codigo_sucursal = LEFT(REPLACE(UPPER(s.sucursal_nombre), ' ', ''), 10)
  )
GROUP BY 
    s.sucursal_nombre, 
    s.direccion_sucursal, 
    c.id_comuna;

-- de Lugares 
INSERT INTO lugar (
    codigo_lugar, 
    nombre, 
    capacidad, 
    codigo_sucursal, 
    tipo_lugar
)
SELECT 
    LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15), 
    MAX(lugar_nombre), 
    MAX(CAST(capacidad_personas AS integer)), 
    MAX(LEFT(REPLACE(UPPER(sucursal_nombre), ' ', ''), 10)), 
    MAX(tipo_lugar)
FROM stg_sucursales_lugares
WHERE lugar_nombre IS NOT NULL 
  AND lugar_nombre != '' 
  AND capacidad_personas != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM lugar 
      -- hacemos el codigo como la combinacion de la sucursal y el lugar pero comoo maximo 15caracteres pq es varchar(15)
      WHERE lugar.codigo_lugar = LEFT(REPLACE(UPPER(stg_sucursales_lugares.sucursal_nombre || '_' || stg_sucursales_lugares.lugar_nombre), ' ', ''), 15)
  )
-- 
GROUP BY LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15);

-- de Precio Lugares
INSERT INTO precio_lugar (
    codigo_lugar, 
    tipo_precio, 
    dia_semana, 
    hora_inicio, 
    hora_termino, 
    fecha_inicio, 
    fecha_fin, 
    monto
)
SELECT 
    LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15), 
    tipo_precio, 
    dia_semana, 
    CAST(hora_inicio AS time), 
    CAST(hora_termino AS time), 
    CAST(fecha_inicio_vigencia AS date), 
    CAST(fecha_fin_vigencia AS date), 
    CAST(precio AS integer)
FROM stg_sucursales_lugares
WHERE precio IS NOT NULL 
  AND precio != '' 
  AND hora_inicio != '' 
  AND hora_termino != '' 
  AND fecha_inicio_vigencia != '' 
  AND fecha_fin_vigencia != '' 
  AND lugar_nombre IS NOT NULL 
  AND lugar_nombre != '';

-- de Personas 
INSERT INTO persona (
    run, 
    nombre_completo, 
    email, 
    telefono_celular, 
    telefono_alternativo, 
    direccion_calle, 
    codigo_comuna, 
    fecha_nacimiento
)
SELECT 
    s.run_persona, 
    MAX(s.nombre_completo), 
    MAX(s.email), 
    MAX(s.telefono_celular), 
    MAX(s.telefono_alternativo), 
    MAX(s.direccion_calle), 
    MAX(CAST(c.id_comuna AS integer)), 
    MAX(CAST(s.fecha_nacimiento AS date))
FROM stg_personas_socios s
LEFT JOIN stg_regiones_comunas c 
    ON TRIM(UPPER(c.nombre_comuna)) = TRIM(UPPER(s.comuna_nombre))
WHERE s.run_persona IS NOT NULL 
  AND s.run_persona != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM persona 
      WHERE persona.run = s.run_persona
  )
GROUP BY s.run_persona;

-- de Personas  extrasque vienen desde reservas
INSERT INTO persona (run, nombre_completo)
SELECT 
    run_reservante, 
    MAX(nombre_reservante)
FROM stg_reservas_arriendos 
WHERE run_reservante IS NOT NULL 
  AND run_reservante != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM persona 
      WHERE persona.run = stg_reservas_arriendos.run_reservante
  )
GROUP BY run_reservante;

-- de Personas extras q son Clientes y contactos de eventos
INSERT INTO persona (run, nombre_completo)
SELECT 
    run_cliente, 
    MAX(nombre_cliente) 
FROM stg_eventos 
WHERE tipo_cliente = 'persona' 
  AND run_cliente IS NOT NULL 
  AND run_cliente != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM persona 
      WHERE persona.run = stg_eventos.run_cliente
  ) 
GROUP BY run_cliente;

INSERT INTO persona (run, nombre_completo)
SELECT 
    rut_contacto_empresa, 
    MAX(nombre_contacto_empresa) 
FROM stg_eventos 
WHERE tipo_cliente = 'empresa-institucion' 
  AND rut_contacto_empresa IS NOT NULL 
  AND rut_contacto_empresa != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM persona 
      WHERE persona.run = stg_eventos.rut_contacto_empresa
  ) 
GROUP BY rut_contacto_empresa;

-- de nacimiento
INSERT INTO naci (run, nac)
SELECT 
    run_persona, 
    CAST(fecha_nacimiento AS date) 
FROM stg_personas_socios 
WHERE run_persona IS NOT NULL 
  AND run_persona != '' 
  AND fecha_nacimiento IS NOT NULL 
  AND fecha_nacimiento != '' 
GROUP BY 
    run_persona, 
    fecha_nacimiento;

-- de Socios
INSERT INTO socio (run_persona, tipo_socio, fecha_inicio, fecha_fin, codigo_sucursal_base)
SELECT 
    run_persona, 
    tipo_persona, 
    CAST(fecha_inicio_membresia AS date), 
    CASE 
        WHEN fecha_fin_membresia = '' THEN NULL 
        ELSE CAST(fecha_fin_membresia AS date) 
    END, 
    LEFT(REPLACE(UPPER(sucursal_base_nombre), ' ', ''), 10)
FROM stg_personas_socios
WHERE run_persona IS NOT NULL 
  AND tipo_persona IN ('socio_titular', 'adicional', 'beneficiario', 'invitado') 
  AND run_persona IN (SELECT run FROM persona) 
  AND NOT EXISTS (
      SELECT 1 
      FROM socio 
      WHERE socio.run_persona = stg_personas_socios.run_persona
  )
GROUP BY 
    run_persona, 
    tipo_persona, 
    fecha_inicio_membresia, 
    fecha_fin_membresia, 
    sucursal_base_nombre;

-- de Membresias
INSERT INTO membresia (id_socio, id_socio_titular, anio, fecha_inicio, fecha_fin, monto_base)
SELECT 
    so.id_socio, 
    so.id_socio, 
    CAST(EXTRACT(YEAR FROM CAST(stg.fecha_inicio_membresia AS date)) AS integer), 
    CAST(stg.fecha_inicio_membresia AS date), 
    CASE 
        WHEN stg.fecha_fin_membresia = '' THEN NULL 
        ELSE CAST(stg.fecha_fin_membresia AS date) 
    END, 
    0
FROM stg_personas_socios stg
JOIN socio so ON stg.run_persona = so.run_persona
WHERE stg.tipo_persona = 'socio_titular' 
  AND NOT EXISTS (
      SELECT 1 
      FROM membresia 
      WHERE membresia.id_socio = so.id_socio
  );

-- de Usuarios
INSERT INTO usuario (run_persona, email_login, clave_encriptada, tipo_usuario)
SELECT 
    run_persona, 
    email, 
    clave_en_texto_plano, 
    tipo_usuario
FROM stg_personas_socios
WHERE es_usuario_sistema = 'SI' 
  AND clave_en_texto_plano IS NOT NULL 
  AND clave_en_texto_plano != '' 
  AND run_persona IN (SELECT run FROM persona) 
  AND NOT EXISTS (
      SELECT 1 
      FROM usuario 
      WHERE usuario.run_persona = stg_personas_socios.run_persona
  )
GROUP BY 
    run_persona, 
    email, 
    clave_en_texto_plano, 
    tipo_usuario;

-- de Relacion Socio (titulares y dependientes)
INSERT INTO relacion_socio (id_socio_titular, id_socio_dependiente, parentesco)
SELECT 
    s_titular.id_socio, 
    s_dep.id_socio, 
    stg.parentesco
FROM stg_personas_socios stg
JOIN socio s_dep ON s_dep.run_persona = stg.run_persona
JOIN socio s_titular ON s_titular.run_persona = stg.run_socio_titular
WHERE stg.tipo_persona IN ('adicional', 'beneficiario', 'invitado') 
  AND stg.run_socio_titular IS NOT NULL 
  AND stg.run_socio_titular != '';

-- de Empresa 
INSERT INTO empresa (rut_empresa, nombre)
SELECT 
    run_cliente, 
    nombre_cliente 
FROM stg_eventos 
WHERE tipo_cliente = 'empresa-institucion' 
  AND run_cliente IS NOT NULL 
  AND run_cliente != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM empresa 
      WHERE empresa.rut_empresa = stg_eventos.run_cliente
  ) 
GROUP BY 
    run_cliente, 
    nombre_cliente;

-- de Contacto Empresa
INSERT INTO contacto_empresa (rut_empresa, run_persona, nombre, cargo)
SELECT 
    run_cliente, 
    rut_contacto_empresa, 
    nombre_contacto_empresa, 
    cargo_contacto 
FROM stg_eventos 
WHERE tipo_cliente = 'empresa-institucion' 
  AND run_cliente IS NOT NULL 
  AND run_cliente != '' 
  AND rut_contacto_empresa IN (SELECT run FROM persona) 
  AND NOT EXISTS (
      SELECT 1 
      FROM contacto_empresa 
      WHERE contacto_empresa.rut_empresa = stg_eventos.run_cliente 
        AND contacto_empresa.run_persona = stg_eventos.rut_contacto_empresa
  ) 
GROUP BY 
    run_cliente, 
    rut_contacto_empresa, 
    nombre_contacto_empresa, 
    cargo_contacto;

-- de eventos 
INSERT INTO evento (codigo_evento, nombre, fecha_evento, codigo_lugar, codigo_sucursal, tipo_cliente, identificador_cliente)
SELECT 
    evento_id, 
    nombre_evento, 
    CAST(fecha_evento AS date), 
    LEFT(REPLACE(UPPER(sucursal_nombre || '_' || lugar_nombre), ' ', ''), 15), 
    LEFT(REPLACE(UPPER(sucursal_nombre), ' ', ''), 10), 
    tipo_cliente, 
    run_cliente 
FROM stg_eventos 
WHERE evento_id IS NOT NULL 
  AND evento_id != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM evento 
      WHERE evento.codigo_evento = stg_eventos.evento_id
  ) 
GROUP BY 
    evento_id, 
    nombre_evento, 
    fecha_evento, 
    sucursal_nombre, 
    lugar_nombre, 
    tipo_cliente, 
    run_cliente;

-- de pagos de eventos

INSERT INTO pago_evento (codigo_evento, fecha_pago, monto, tipo_pago)
SELECT 
    evento_id, 
    CAST(fecha_contratacion AS date), 
    CAST(monto_pagado_reserva AS integer), 
    'RESERVA' 
FROM stg_eventos 
WHERE monto_pagado_reserva != '' 
  AND monto_pagado_reserva != '0';

INSERT INTO pago_evento (codigo_evento, fecha_pago, monto, tipo_pago)
SELECT 
    evento_id, 
    CAST(fecha_evento AS date), 
    CAST(monto_pagado_ejecucion AS integer), 
    'EJECUCION' 
FROM stg_eventos 
WHERE monto_pagado_ejecucion != '' 
  AND monto_pagado_ejecucion != '0';

-- le ponemos el id a codigo_reserva que no tenia
UPDATE stg_reservas_arriendos SET codigo_reserva = 'RES-' || CAST(id_temporal AS VARCHAR) WHERE codigo_reserva IS NULL OR codigo_reserva = '';

-- de Reserva

INSERT INTO reserva (codigo_reserva, codigo_lugar, run_reservante, fecha_inicio, fecha_fin, estado)
SELECT 
    r.codigo_reserva,
    l.codigo_lugar,
    r.run_reservante,
    CAST(NULLIF(r.fecha_inicio, '') AS timestamp),
    CAST(NULLIF(r.fecha_fin, '') AS timestamp),
    r.estado_reserva

FROM stg_reservas_arriendos r
--  con maximo 15 caracteres para el codigo_lugar
LEFT JOIN lugar l ON l.codigo_lugar = LEFT(REPLACE(UPPER(r.sucursal_nombre || '_' || r.lugar_nombre), ' ', ''), 15)
WHERE r.codigo_reserva IS NOT NULL 
  AND r.codigo_reserva != '' 
  AND r.run_reservante IN (SELECT run FROM persona)
  AND NOT EXISTS (
      SELECT 1 FROM reserva WHERE reserva.codigo_reserva = r.codigo_reserva
  )
GROUP BY r.codigo_reserva, l.codigo_lugar, r.run_reservante, r.fecha_inicio, r.fecha_fin, r.estado_reserva;

INSERT INTO pago_reserva (codigo_reserva, fecha_pago, monto, medio_pago)
SELECT 
    codigo_reserva, 
    CAST(fecha_pago AS date), 
    CAST(monto_pagado AS integer), 
    medio_pago
FROM stg_reservas_arriendos 
WHERE monto_pagado != '' 
  AND monto_pagado != '0' 
  AND codigo_reserva IN (SELECT codigo_reserva FROM reserva);

-- de Cuotas 

INSERT INTO cuota (id_membresia, mes, fecha_vencimiento, monto_total, estado)
SELECT 
    m.id_socio, 
    CAST(stg.mes_cuota AS integer), 
    CAST(stg.fecha_vencimiento AS date), 
    CAST(stg.monto_total AS integer), 
    stg.estado_pago    
FROM stg_pagos_membresias stg 
JOIN socio s ON s.run_persona = stg.run_socio_titular 
JOIN membresia m ON m.id_socio = s.id_socio 
WHERE stg.mes_cuota != '' 
  AND stg.monto_total != '' 
GROUP BY m.id_socio, stg.mes_cuota, stg.fecha_vencimiento, stg.monto_total, stg.estado_pago;

-- de Pago cuotas

INSERT INTO pago_cuota (cuota_numero, fecha_pago, monto_pagado, medio_pago, id_socio)
SELECT 
    c.id_cuota, 
    CAST(stg.fecha_pago AS date), 
    CAST(stg.monto_total AS integer), 
    stg.medio_pago, 
    s.id_socio
FROM stg_pagos_membresias stg 
JOIN socio s ON s.run_persona = stg.run_socio_titular 
JOIN membresia m ON m.id_socio = s.id_socio 
JOIN cuota c ON c.id_membresia = m.id_socio 
    AND c.mes = CAST(stg.mes_cuota AS integer) 
WHERE stg.fecha_pago IS NOT NULL 
  AND stg.fecha_pago != '' 
GROUP BY c.id_cuota, stg.fecha_pago, stg.monto_total, stg.medio_pago, s.id_socio;

-- de Cargos 

INSERT INTO cargo (nombre)
SELECT 
    nombre_cargo 
FROM stg_cargos_administrativos 
WHERE nombre_cargo IS NOT NULL 
  AND nombre_cargo != '' 
  AND NOT EXISTS (
      SELECT 1 
      FROM cargo 
      WHERE cargo.nombre = stg_cargos_administrativos.nombre_cargo
  ) 
GROUP BY nombre_cargo;

-- de persona cargo

INSERT INTO persona_cargo (run_persona, id_cargo, codigo_sucursal, fecha_inicio, fecha_termino)
SELECT 
    stg.run_persona, 
    c.id_cargo, 
    LEFT(REPLACE(UPPER(stg.sucursal_nombre), ' ', ''), 10), 
    CAST(stg.fecha_inicio_cargo AS date), 
    CASE 
        WHEN stg.fecha_termino_cargo != '' THEN CAST(stg.fecha_termino_cargo AS date) 
        ELSE NULL 
    END
FROM stg_cargos_administrativos stg 
JOIN cargo c ON c.nombre = stg.nombre_cargo 
WHERE stg.run_persona IS NOT NULL 
  AND stg.run_persona != '' 
  AND stg.run_persona IN (SELECT run FROM persona) 
  AND LEFT(REPLACE(UPPER(stg.sucursal_nombre), ' ', ''), 10) IN (SELECT codigo_sucursal FROM sucursal) 
GROUP BY 
    stg.run_persona, 
    c.id_cargo, 
    stg.sucursal_nombre, 
    stg.fecha_inicio_cargo, 
    stg.fecha_termino_cargo;

-- hacemos un SP para cargar asistentes

CREATE OR REPLACE PROCEDURE sp_cargar_asistentes()
LANGUAGE plpgsql AS $$
DECLARE
    r RECORD;
    asistente TEXT;
BEGIN
    FOR r IN SELECT e.codigo_evento, s.lista_asistentes FROM evento e JOIN stg_eventos s ON e.nombre = s.nombre_evento WHERE s.lista_asistentes IS NOT NULL AND s.lista_asistentes != '' LOOP
        FOREACH asistente IN ARRAY string_to_array(r.lista_asistentes, ';') LOOP
            INSERT INTO asistente_evento (codigo_evento, nombre_asistente) VALUES (r.codigo_evento, TRIM(asistente));
        END LOOP;
    END LOOP;
END;
$$;

CALL sp_cargar_asistentes();



\copy (SELECT 'poblamos correctamente las tablas') TO 'cargaLOG.txt' WITH (FORMAT text);

COMMIT;